version: '3.9'

services:
  ${DOCKER_SERVICE_NAME}:
    container_name: ${DOCKER_SERVICE_NAME}
    image: uniclienttechnologies/${DOCKER_SERVICE_NAME}:latest
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - '/var/www/uploads:/uploads'
      - './logs:/app/logs'
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    restart: always
    networks:
      - wagehat-net

networks:
  wagehat-net:
    driver: bridge
